# TODO: Fix this Makefile duplication.  This file just adds the
# compiler option -mmacosx-version-min=13.3

CXXFLAGS = -Wall -Werror -std=c++17 -mmacosx-version-min=13.3 -I../include

all: demo readme_example

demo: demo.cpp
	g++ $(CXXFLAGS) demo.cpp -o demo

readme_example: readme_example.cpp
	g++ $(CXXFLAGS) readme_example.cpp -o readme_example

clean:
	rm -rf demo
